[app]
# Interface and port where the app will run its webserver.
address = "localhost:9000"

# BasicAuth authentication for the admin dashboard. This will eventually
# be replaced with a better multi-user, role-based authentication system.
# IMPORTANT: Leave both values empty to disable authentication on admin
# only where an external authentication is already setup.
admin_username = "listmonk"
admin_password = "<your_password>"

# Database.
[db]
host = "localhost"
port = 5432
user = "listmonk"
password = "listmonk"
database = "<your_password>"
ssl_mode = "disable"
max_open = 25
max_idle = 25
max_lifetime = "300s"
